### ISSUE TITLE
real good theme for vsc。

### ISSUE THREAD

**Issue by RivTian** [TroddenSpade/Samurai-theme-vscode#1]
This theme is great, but for me it has a flaw: the comments are not clear.  How can to adjust it.  Thank you！

![](https://gitee.com//riotian/blogimage/raw/master/img/20201203203528.png)

**Comment by TroddenSpade** [comment]
Hi @RivTian, I'm glad that you liked the theme. I fixed the low opacity problem for comments and also added a new Theme to this package.
I hope you enjoy it!
